version: '3.8'

services:
  backend:
    image: yashparmar2055/blog-website-backend:latest  # You can also push this to Docker Hub if needed
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    depends_on:
      - mongo

  frontend:
    image: yashparmar2055/my-frontend:latest  # Use public Docker Hub image
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
