# Use Node.js image
FROM node:18

# Set working directory inside container
WORKDIR /app

# Copy backend package files
COPY api/package*.json ./

# Install backend dependencies
RUN npm install

# Install nodemon globally for development
RUN npm install -g nodemon

# Copy backend source code
COPY api/ .

# Expose API port
EXPOSE 3000

# Run the backend in dev mode
CMD ["npm", "run", "dev"]
